<a href="https://colab.research.google.com/github/primroseisaseal/Cryptocurrencies-forecast/blob/main/No_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [128]:
pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: yfinance in /usr/local/lib/python3.7/dist-packages (0.1.74)
Requirement already satisfied: requests>=2.26 in /usr/local/lib/python3.7/dist-packages (from yfinance) (2.28.1)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: lxml>=4.5.1 in /usr/local/lib/python3.7/dist-packages (from yfinance) (4.9.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.6.15)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)

In [129]:
pip install TA-Lib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting TA-Lib
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from TA-Lib) (1.21.6)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (setup.py) ... error
  ERROR: Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c4irt51e/ta-lib_d2e78de9dac14ad9ba540f102b686f10/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c4irt51e/ta-lib_d2e78de9dac14ad9ba540f102b686f10/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ove0edim/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/TA-Lib Check the logs for full command output.

In [130]:
pip install pandas-datareader

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas-datareader in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (4.9.1)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (2.28.1)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (1.3.5)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (1.21.6)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.15.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (1.24.3)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2.1.0)

In [131]:
pip install ta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: ta in /usr/local/lib/python3.7/dist-packages (0.10.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from ta) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from ta) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->ta) (1.15.0)

In [132]:
pip install TA-Lib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting TA-Lib
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from TA-Lib) (1.21.6)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (setup.py) ... error
  ERROR: Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-_u34hqkt/ta-lib_7f08f746df724fb8a9ab6739cec89311/setup.py'"'"'; __file__='"'"'/tmp/pip-install-_u34hqkt/ta-lib_7f08f746df724fb8a9ab6739cec89311/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4z1ealjg/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/TA-Lib Check the logs for full command output.

In [133]:
import pandas as pd
from sklearn import linear_model
import yfinance as yf
from pandas_datareader import data as pdr
import matplotlib.pyplot as plt
# import pandas_profiling
# from pandas_profiling import ProfileReport
import matplotlib.pyplot as plt
import ta
from ta.trend import macd
from ta import momentum
from ta import trend
from ta import volatility
from ta import volume
# import talib
# from talib import ADOSC

In [134]:
yf.pdr_override() # 
# download dataframe
BTC = pdr.get_data_yahoo("BTC", start="2019-01-01", end="2022-06-15")
BTC
gold = pdr.get_data_yahoo("GC=F", start="2019-01-01", end="2022-06-15")
gold
DJI = pdr.get_data_yahoo("^DJI", start="2019-01-01", end="2022-06-15")
oil = pdr.get_data_yahoo("CL=F", start="2019-01-01", end="2022-06-15")
usdeur = pdr.get_data_yahoo("EUR=X", start="2019-01-01", end="2022-06-15")
usdcny = pdr.get_data_yahoo("CNY=X", start="2019-01-01", end="2022-06-15")

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [135]:
# Market cap

def get_features_14(data):
  data['MACD'] = macd(data['Close'], window_slow = 26, window_fast = 12,fillna = True)
  data['PPO'] = momentum.ppo(data['Close'], window_slow = 26, window_fast = 12,fillna = True)
  data['CCI'] = trend.cci(data['High'], data['Low'], data['Close'] ,fillna = True)
  data['ROC'] = momentum.roc(data['Close'],fillna = True)
  data['Stochastic Oscillator'] = momentum.stoch(data['High'], data['Low'], data['Close'] ,fillna = True)
  data['Williams_r'] = momentum.williams_r(data['High'], data['Low'], data['Close'] ,fillna = True)
  data['SMA_20'] =trend.sma_indicator(data['Close'], window =20, fillna =True)
  data['SMA_50'] =trend.sma_indicator(data['Close'], window =50, fillna =True)
  data['SMA_100'] =trend.sma_indicator(data['Close'], window =100, fillna =True)
  data['EMA_20'] =trend.ema_indicator(data['Close'], window =20, fillna =True)
  data['EMA_50'] =trend.ema_indicator(data['Close'], window =50, fillna =True)
  data['EMA_100'] =trend.ema_indicator(data['Close'], window =100, fillna =True)
  data['Bollinger_Bands_L'] = volatility.bollinger_lband(data['Close'], fillna =True)
  data['Bollinger_Bands_M'] = volatility.bollinger_mavg(data['Close'], fillna =True) 
  data['Bollinger_Bands_H'] = volatility.bollinger_hband(data['Close'], fillna =True)
  data['OBV'] = volume.on_balance_volume(data['Close'], data['Volume'], fillna =True)
  data['Chaikin'] = volume.chaikin_money_flow(data['High'], data['Low'], data['Close'], data['Volume'], fillna =True)
  data['MFI'] = volume.money_flow_index(data['High'], data['Low'], data['Close'], data['Volume'], fillna =True)
  data['ATR'] = volatility.average_true_range(data['High'], data['Low'], data['Close'] ,fillna = True)
  data['Open_RSI'] = momentum.rsi(data['Open'], fillna = True)
  data['Close_RSI'] = momentum.rsi(data['Close'], fillna = True)
  return data

In [136]:
BTC_featues = get_features_14(BTC)
BTC_featues

,Open,High,Low,Close,Adj Close,Volume,MACD,PPO,CCI,ROC,...,EMA_100,Bollinger_Bands_L,Bollinger_Bands_M,Bollinger_Bands_H,OBV,Chaikin,MFI,ATR,Open_RSI,Close_RSI
Date,,,,,,,,,,,,,,,,,,,,,
2020-10-01,100.000000,100.000000,100.000000,100.000000,100.000000,0,0.000000,0.000000,0.000000,0.000000,...,100.000000,100.000000,100.000000,100.000000,0,0.000000,50.000000,0.000000,100.000000,100.000000
2020-10-02,100.000000,100.000000,100.000000,100.000000,100.000000,0,0.000000,0.000000,0.000000,0.000000,...,100.000000,100.000000,100.000000,100.000000,0,0.000000,50.000000,0.000000,100.000000,100.000000
2020-10-05,100.029999,100.040001,99.995003,99.995003,99.995003,10725,-0.000399,-0.000399,100.000000,0.000000,...,99.999901,99.993623,99.998334,100.003046,-10725,-1.000000,100.000000,0.000000,100.000000,0.000000
2020-10-06,100.010002,100.029999,100.010002,100.029999,100.029999,10080,0.002085,0.002085,119.987794,0.000000,...,100.000497,99.978526,100.006250,100.033975,-645,-0.031002,100.000000,0.000000,58.212049,88.292797
2020-10-07,99.949997,99.959999,99.919998,99.919998,99.919998,6350,-0.004767,-0.004768,-166.666667,0.000000,...,99.998903,99.915678,99.989000,100.062322,-6995,-0.257595,76.630618,0.000000,24.766704,22.135583
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-06-08,93.175003,93.175003,93.175003,93.175003,93.175003,3,-0.072190,-0.077178,-101.149031,-0.464261,...,94.896648,92.928089,93.520374,94.112659,-454789,-0.501098,22.858372,0.205668,42.096260,42.288870
2022-06-09,93.079597,93.079597,93.050003,93.050003,93.050003,181,-0.100002,-0.106952,-126.119211,-0.396056,...,94.860081,92.886469,93.507375,94.128280,-454970,-0.523417,21.539319,0.199906,40.430968,40.206478
2022-06-10,92.720001,92.720001,92.432602,92.432602,92.432602,153,-0.169904,-0.181866,-220.382125,-1.470807,...,94.812012,92.676924,93.455020,94.233116,-455123,-0.542489,20.412814,0.229727,34.837071,31.861202
2022-06-13,91.769997,91.769997,91.527000,91.527000,91.527000,114,-0.294976,-0.316219,-311.844076,-2.639029,...,94.746962,92.220357,93.366120,94.511882,-455237,-0.554798,19.777394,0.278004,24.997240,23.994253
2022-06-14,91.178398,91.178398,91.178398,91.178398,91.178398,18,-0.417413,-0.448223,-277.904249,-3.094482,...,94.676298,91.763042,93.251290,94.739538,-455255,-0.549991,14.832267,0.283047,21.016279,21.766298

In [137]:
# get gold data
def get_gold_data(gold):
  gold['Movement_gold_Open'] = gold['Open'].diff(periods=1).fillna(0)
  gold['Open_RSI'] = momentum.rsi(gold['Open'], fillna = True)
  gold['Close_RSI'] = momentum.rsi(gold['Close'], fillna = True)
  gold = gold.iloc[:,6:]
  prefix = 'gold_'
  gold = gold.add_prefix(prefix)
  return gold

gold = get_gold_data(gold)
gold

            gold_Movement_gold_Open  gold_Open_RSI  gold_Close_RSI
Date
2019-01-02                 0.000000     100.000000      100.000000
2019-01-03                 0.800049     100.000000      100.000000
2019-01-04                 7.399902     100.000000       52.427030
2019-01-07                -7.399902      50.538977       61.348884
2019-01-08                -6.300049      34.770828       52.108171
...                             ...            ...             ...
2022-06-08                 7.900024      46.954959       48.228109
2022-06-09                 1.299927      47.336952       47.237563
2022-06-10                -3.400024      46.395848       54.592126
2022-06-13                31.100098      55.174481       42.396348
2022-06-14               -48.800049      43.215133       38.461130

[871 rows x 3 columns]

In [138]:
def get_data_DJI(DJI):
  DJI['Open_SMA50'] = trend.sma_indicator(DJI['Open'], window =50, fillna =True)
  DJI = DJI[['Volume', 'Open_SMA50']]
  prefix = 'DJI_'
  DJI = DJI.add_prefix(prefix)
  return DJI

DJI = get_data_DJI(DJI)

In [139]:
def get_data_oil(oil):
  oil['Diff_close'] = oil['Close'].diff(periods=1).fillna(0)
  oil = oil[['Volume', 'Diff_close']]
  prefix = 'oil_'
  oil = oil.add_prefix(prefix)
  return oil

oil = get_data_oil(oil)
oil

            oil_Volume  oil_Diff_close
Date
2019-01-02      850480        0.000000
2019-01-03      788718        0.549999
2019-01-04      817277        0.869999
2019-01-07      819939        0.560001
2019-01-08      765981        1.259998
...                ...             ...
2022-06-08      340591        2.699997
2022-06-09      293295       -0.599998
2022-06-10      352906       -0.840004
2022-06-13      372403        0.260002
2022-06-14      366320       -2.000000

[871 rows x 2 columns]

In [140]:
def get_data_usdeur(usdeur):
  usdeur['Open_SMA50'] = trend.sma_indicator(usdeur['Open'], window =50, fillna =True)
  usdeur = usdeur[['Open', 'Adj Close', 'Open_SMA50']]
  prefix = 'usdeur_'
  usdeur = usdeur.add_prefix(prefix)
  return usdeur

usdeur = get_data_usdeur(usdeur)
usdeur

            usdeur_Open  usdeur_Adj Close  usdeur_Open_SMA50
Date
2019-01-01      0.87000           0.87009           0.870000
2019-01-02      0.87250           0.87247           0.871250
2019-01-03      0.88360           0.88354           0.875367
2019-01-04      0.87789           0.87788           0.875997
2019-01-07      0.87620           0.87639           0.876038
...                 ...               ...                ...
2022-06-09      0.93304           0.93304           0.934867
2022-06-10      0.94169           0.94169           0.935638
2022-06-13      0.95329           0.95329           0.936600
2022-06-14      0.96014           0.96014           0.937581
2022-06-15      0.95780           0.95780           0.938399

[901 rows x 3 columns]

In [141]:
def get_data_usdcny(usdcny):
  usdcny = usdcny[['Open', 'Close', 'High']]
  prefix = 'usdcny_'
  usdcny = usdcny.add_prefix(prefix)
  
  return usdcny

usdcny = get_data_usdcny(usdcny)
usdcny

            usdcny_Open  usdcny_Close  usdcny_High
Date
2019-01-01       6.8776        6.8776       6.8776
2019-01-02       6.8775        6.8775       6.8785
2019-01-03       6.8611        6.8611       6.8817
2019-01-04       6.8710        6.8711       6.8710
2019-01-07       6.8684        6.8684       6.8697
...                 ...           ...          ...
2022-06-09       6.6827        6.6827       6.6975
2022-06-10       6.6908        6.6908       6.7163
2022-06-13       6.7079        6.7079       6.7582
2022-06-14       6.7535        6.7535       6.7601
2022-06-15       6.7395        6.7395       6.7400

[900 rows x 3 columns]

In [147]:
# get BTC oval all data
def get_overall_data(data, gold, DJI, oil, usdeur, usdcny):
  final_data = data.merge(DJI, on='Date')
  final_data = final_data.merge(gold, on ='Date')
  final_data = final_data.merge(usdeur, on ='Date')
  final_data = final_data.merge(oil, on ='Date')
  final_data = final_data.merge(usdcny, on ='Date')
  return final_data

BTC_all_features = get_overall_data(BTC, gold, DJI, oil, usdeur, usdcny)

In [148]:

# plt.tight_layout()

# fig, axes = plt.subplots(len(BTC_all_features.columns)//3, 3, figsize=(12, 48))

# i = 0
# for triaxis in axes:
#     for axis in triaxis:
#         BTC_all_features.hist(column = BTC_all_features.columns[i], bins = 100, ax=axis)
#         i = i+1

In [149]:
from google.colab import files

# e.g. save pandas output as csv
BTC_all_features.to_csv('BTC_all_features.csv')
files.download('BTC_all_features.csv')