<a href="https://colab.research.google.com/github/primroseisaseal/Cryptocurrencies-forecast/blob/main/No_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
pip install yfinance

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting yfinance
  Downloading yfinance-0.1.74-py2.py3-none-any.whl (27 kB)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.7/dist-packages (from yfinance) (0.0.11)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.3.5)
Collecting requests>=2.26
  Downloading requests-2.28.1-py3-none-any.whl (62 kB)
     |████████████████████████████████| 62 kB 1.4 MB/s
Collecting lxml>=4.5.1
  Downloading lxml-4.9.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (6.4 MB)
     |████████████████████████████████| 6.4 MB 30.7 MB/s
Requirement already satisfied: numpy>=1.15 in /usr/local/lib/python3.7/dist-packages (from yfinance) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.24.0->yfinance) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.24.0->yfinance) (1.15.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2022.6.15)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.10)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.26->yfinance) (2.1.0)
Installing collected packages: requests, lxml, yfinance
  Attempting uninstall: requests
    Found existing installation: requests 2.23.0
    Uninstalling requests-2.23.0:
      Successfully uninstalled requests-2.23.0
  Attempting uninstall: lxml
    Found existing installation: lxml 4.2.6
    Uninstalling lxml-4.2.6:
      Successfully uninstalled lxml-4.2.6
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires requests~=2.23.0, but you have requests 2.28.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
Successfully installed lxml-4.9.1 requests-2.28.1 yfinance-0.1.74

In [ ]:
pip install TA-Lib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting TA-Lib
  Downloading TA-Lib-0.4.24.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 6.9 MB/s
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from TA-Lib) (1.21.6)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (setup.py) ... error
  ERROR: Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-s9tf662q/ta-lib_33fcd4e8fc5b48e8a236dd1ec7088e18/setup.py'"'"'; __file__='"'"'/tmp/pip-install-s9tf662q/ta-lib_33fcd4e8fc5b48e8a236dd1ec7088e18/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-a_t_wbzh/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/TA-Lib Check the logs for full command output.

In [4]:
pip install pandas-datareader

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandas-datareader in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (2.23.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (4.2.6)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.7/dist-packages (from pandas-datareader) (1.3.5)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.23->pandas-datareader) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.23->pandas-datareader) (1.15.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.19.0->pandas-datareader) (2022.6.15)

In [3]:
pip install ta

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting ta
  Downloading ta-0.10.1.tar.gz (24 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from ta) (1.21.6)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from ta) (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->ta) (1.15.0)
Building wheels for collected packages: ta
  Building wheel for ta (setup.py) ... done
  Created wheel for ta: filename=ta-0.10.1-py3-none-any.whl size=28985 sha256=d38d260e9700379fb8f44f07b5e5b41f710af70c30e4eb4bd061a1bc19a90a55
  Stored in directory: /root/.cache/pip/wheels/bc/2a/c2/a56e77d07edc16a1fa7fb012667e55cb0643cfa65996bddecc
Successfully built ta
Installing collected packages: ta
Successfully installed ta-0.10.1

In [52]:
pip install TA-Lib

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting TA-Lib
  Using cached TA-Lib-0.4.24.tar.gz (269 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from TA-Lib) (1.21.6)
Building wheels for collected packages: TA-Lib
  Building wheel for TA-Lib (setup.py) ... error
  ERROR: Failed building wheel for TA-Lib
  Running setup.py clean for TA-Lib
Failed to build TA-Lib
Installing collected packages: TA-Lib
    Running setup.py install for TA-Lib ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7z3o9zit/ta-lib_3961b6174b6b4a8294b4c4f82d8730c4/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7z3o9zit/ta-lib_3961b6174b6b4a8294b4c4f82d8730c4/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-yq4itz_o/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/TA-Lib Check the logs for full command output.

In [58]:
import pandas as pd
from sklearn import linear_model
import yfinance as yf
from pandas_datareader import data as pdr
import matplotlib.pyplot as plt
# import pandas_profiling
# from pandas_profiling import ProfileReport
import matplotlib.pyplot as plt
import ta
from ta.trend import macd
from ta import momentum
from ta import trend
from ta import volatility
from ta import volume
# import talib
# from talib import ADOSC

In [59]:
yf.pdr_override() # 
# download dataframe
BTC = pdr.get_data_yahoo("BTC", start="2019-01-01", end="2022-06-15")
BTC

[*********************100%***********************]  1 of 1 completed

                  Open        High         Low       Close   Adj Close  Volume
Date
2020-10-01  100.000000  100.000000  100.000000  100.000000  100.000000       0
2020-10-02  100.000000  100.000000  100.000000  100.000000  100.000000       0
2020-10-05  100.029999  100.040001   99.995003   99.995003   99.995003   10725
2020-10-06  100.010002  100.029999  100.010002  100.029999  100.029999   10080
2020-10-07   99.949997   99.959999   99.919998   99.919998   99.919998    6350
...                ...         ...         ...         ...         ...     ...
2022-06-08   93.175003   93.175003   93.175003   93.175003   93.175003       3
2022-06-09   93.079597   93.079597   93.050003   93.050003   93.050003     181
2022-06-10   92.720001   92.720001   92.432602   92.432602   92.432602     153
2022-06-13   91.769997   91.769997   91.527000   91.527000   91.527000     114
2022-06-14   91.178398   91.178398   91.178398   91.178398   91.178398      18

[429 rows x 6 columns]

In [60]:
# Market cap

def get_features(data):
  data['MACD'] = macd(data['Close'], window_slow = 26, window_fast = 12,fillna = True)
  data['PPO'] = momentum.ppo(data['Close'], window_slow = 26, window_fast = 12,fillna = True)
  data['CCI'] = trend.cci(data['High'], data['Low'], data['Close'] ,fillna = True)
  data['ROC'] = momentum.roc(data['Close'],fillna = True)
  data['Stochastic Oscillator'] = momentum.stoch(data['High'], data['Low'], data['Close'] ,fillna = True)
  data['Williams_r'] = momentum.williams_r(data['High'], data['Low'], data['Close'] ,fillna = True)
  data['SMA_20'] =trend.sma_indicator(data['Close'], window =20, fillna =True)
  data['SMA_50'] =trend.sma_indicator(data['Close'], window =50, fillna =True)
  data['SMA_100'] =trend.sma_indicator(data['Close'], window =100, fillna =True)
  data['EMA_20'] =trend.ema_indicator(data['Close'], window =20, fillna =True)
  data['EMA_50'] =trend.ema_indicator(data['Close'], window =50, fillna =True)
  data['EMA_100'] =trend.ema_indicator(data['Close'], window =100, fillna =True)
  data['Bollinger_Bands_L'] = volatility.bollinger_lband(data['Close'], fillna =True)
  data['Bollinger_Bands_M'] = volatility.bollinger_mavg(data['Close'], fillna =True) 
  data['Bollinger_Bands_H'] = volatility.bollinger_hband(data['Close'], fillna =True)
  data['OBV'] = volume.on_balance_volume(data['Close'], data['Volume'], fillna =True)
  data['Chaikin'] = volume.chaikin_money_flow(data['High'], data['Low'], data['Close'], data['Volume'], fillna =True)
  data['MFI'] = volume.money_flow_index(data['High'], data['Low'], data['Close'], data['Volume'], fillna =True)
  data['ATR'] = volatility.average_true_range(data['High'], data['Low'], data['Close'] ,fillna = True)
  return data

In [61]:
BTC_featues = get_features(BTC)
BTC_featues

,Open,High,Low,Close,Adj Close,Volume,MACD,PPO,CCI,ROC,...,EMA_20,EMA_50,EMA_100,Bollinger_Bands_L,Bollinger_Bands_M,Bollinger_Bands_H,OBV,Chaikin,MFI,ATR
Date,,,,,,,,,,,,,,,,,,,,,
2020-10-01,100.000000,100.000000,100.000000,100.000000,100.000000,0,0.000000,0.000000,0.000000,0.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,0,0.000000,50.000000,0.000000
2020-10-02,100.000000,100.000000,100.000000,100.000000,100.000000,0,0.000000,0.000000,0.000000,0.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,0,0.000000,50.000000,0.000000
2020-10-05,100.029999,100.040001,99.995003,99.995003,99.995003,10725,-0.000399,-0.000399,100.000000,0.000000,...,99.999524,99.999804,99.999901,99.993623,99.998334,100.003046,-10725,-1.000000,100.000000,0.000000
2020-10-06,100.010002,100.029999,100.010002,100.029999,100.029999,10080,0.002085,0.002085,119.987794,0.000000,...,100.002426,100.000988,100.000497,99.978526,100.006250,100.033975,-645,-0.031002,100.000000,0.000000
2020-10-07,99.949997,99.959999,99.919998,99.919998,99.919998,6350,-0.004767,-0.004768,-166.666667,0.000000,...,99.994576,99.997812,99.998903,99.915678,99.989000,100.062322,-6995,-0.257595,76.630618,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-06-08,93.175003,93.175003,93.175003,93.175003,93.175003,3,-0.072190,-0.077178,-101.149031,-0.464261,...,93.497322,93.910527,94.896648,92.928089,93.520374,94.112659,-454789,-0.501098,22.858372,0.205668
2022-06-09,93.079597,93.079597,93.050003,93.050003,93.050003,181,-0.100002,-0.106952,-126.119211,-0.396056,...,93.454720,93.876781,94.860081,92.886469,93.507375,94.128280,-454970,-0.523417,21.539319,0.199906
2022-06-10,92.720001,92.720001,92.432602,92.432602,92.432602,153,-0.169904,-0.181866,-220.382125,-1.470807,...,93.357375,93.820147,94.812012,92.676924,93.455020,94.233116,-455123,-0.542489,20.412814,0.229727
2022-06-13,91.769997,91.769997,91.527000,91.527000,91.527000,114,-0.294976,-0.316219,-311.844076,-2.639029,...,93.183054,93.730219,94.746962,92.220357,93.366120,94.511882,-455237,-0.554798,19.777394,0.278004
2022-06-14,91.178398,91.178398,91.178398,91.178398,91.178398,18,-0.417413,-0.448223,-277.904249,-3.094482,...,92.992134,93.630148,94.676298,91.763042,93.251290,94.739538,-455255,-0.549991,14.832267,0.283047